trigger:
  branches:
    include:
      - master

variables:
  keyvault_name: "infraautomator-keyvault"

steps:
  - task: AzureKeyVault@1
    displayName: "Download the Keyvault secrets"
    inputs:
      azureSubscription: 'ARM'
      KeyVaultName: $(keyvault_name)
      SecretsFilter: 'vmAdminUsername,vmAdminPassword'
  - task: TerraformCLI@0
    displayName: "Download Terraform providers"
    inputs:
      command: 'init'
  - task: TerraformCLI@0
    displayName: "Test Terraform plan"
    inputs:
      command: 'plan'
      environmentServiceName: 'ARM'
      commandOptions: '-input=false --var="vmAdminUsername=$(vmAdminUsername)" --var="vmAdminPassword=$(vmAdminPassword)"'
  - task: TerraformCLI@0
    displayName: "Build the VM"
    inputs:
      command: 'apply'
      environmentServiceName: 'ARM'
      commandOptions: '-input=false --var="vmAdminUsername=$(vmAdminUsername)" --var="vmAdminPassword=$(vmAdminPassword)"'
  - task: Pester@10
    displayName: "Run the infrastructure tests"
    inputs:
      scriptFolder: '$(System.DefaultWorkingDirectory)/tests'
      resultsFile: '$(System.DefaultWorkingDirectory)/tests/results.XML'
      usePSCore: True
  - task: PublishTestResults@2
    displayName: "Publish the test results to the pipeline"
    inputs:
      testResultsFormat: "NUnit"
      testResultsFiles: "$(workingDir)/tests/results.xml"
      failTaskOnFailedTests: true