trigger:
  branches:
    include:
      - master

variables:
  keyvault_name: "infraautomator-keyvault"

steps:
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'ARM'
      KeyVaultName: $(keyvault_name)
      SecretsFilter: 'vmAdminUsername,vmAdminPassword'
  - task: TerraformCLI@0
    displayName: "Download Terraform providers"
    inputs:
      command: 'init'
  - task: TerraformCLI@0
    displayName: "Test Terraform plan for VM"
    inputs:
      command: 'plan'
      environmentServiceName: 'ARM'
      commandOptions: '--var=vmAdminUserName="$(vmAdminUserName)" --var=vmAdminUserName="$(vmAdminPassword)"'
  - task: TerraformCLI@0
    displayName: "Build the VM"
    inputs:
      command: 'apply'
      environmentServiceName: 'ARM'
      commandOptions: '--var=vmAdminUserName="$(vmAdminUserName)" --var=vmAdminUserName="$(vmAdminPassword)"'
  - task: Pester@10
    inputs:
      scriptFolder: '$(System.DefaultWorkingDirectory)\tests'
      resultsFile: '$(System.DefaultWorkingDirectory)\tests\results.XML'
      usePSCore: True
  - task: PowerShell@2
    displayName: "Run Pester tests"
    inputs:
      azureSubscription: 'ARM'
      ScriptType: 'FilePath'
      ScriptPath: '$(workingDir)/tests/invoke-test.ps1'
      ScriptArguments: '$(System.DefaultWorkingDirectory)/tests'
      FailOnStandardError: true
      azurePowerShellVersion: 'LatestVersion'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "NUnit"
      testResultsFiles: "$(workingDir)/tests/results.xml"
      failTaskOnFailedTests: true